
name: Daily Premium Key Generator

on:

  schedule:
    
    - cron: '0 17 * * *'

  workflow_dispatch:

jobs:

  generate-keys:
    
    runs-on: ubuntu-latest

    steps:
      
      - name: Checkout repository
        uses: actions/checkout@v3


      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      
      - name: Install Firebase Admin SDK
        run: npm install firebase-admin

      
      - name: Run Key Generation Script

        env:
          FIREBASE_SERVICE_ACCOUNT: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
        run: node generate-keys.js

