# Nama alur kerja Anda
name: Daily Premium Key Generator

on:
  # Menjalankan alur kerja ini sesuai jadwal
  schedule:
    # Ini adalah jadwal cron "setiap hari pada jam 18:00 UTC"
    # 18:00 UTC sama dengan jam 01:00 pagi WIB (GMT+7)
    - cron: '0 18 * * *'
  # Juga izinkan untuk dijalankan secara manual dari tab Actions
  workflow_dispatch:

jobs:
  # Nama pekerjaan
  generate-keys:
    # Menjalankan di server Ubuntu terbaru yang disediakan GitHub
    runs-on: ubuntu-latest

    steps:
      # 1. Mengunduh kode dari repositori Anda
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Menyiapkan lingkungan Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # 3. Masuk ke direktori yang benar SEBELUM menginstal
      - name: Change working directory
        run: cd ghostkeygen

      # 4. Menginstal library Firebase Admin dari dalam direktori yang benar
      #    Kita akan membuat file package.json sederhana agar ini bekerja
      - name: Create package.json and Install Firebase Admin
        working-directory: ./ghostkeygen
        run: |
          echo '{ "dependencies": { "firebase-admin": "^11.0.0" } }' > package.json
          npm install

      # 5. Menjalankan skrip pembuat kunci dari dalam direktori yang benar
      - name: Run Key Generation Script
        working-directory: ./ghostkeygen
        run: node generate-keys.js
        env:
          FIREBASE_SERVICE_ACCOUNT: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}

